c++并发编程     线程管控

#####                                                                    第一章                    你好，并发世界

​	

```c++
void function(){
    std::cout<<"hello concurrent world!";
}

int main(){
    std::thread thd;
    thd.join();
}
```

##### 																	第二章                     线程的基本管控

###### 	2.1.1	发起线程

​		              使用仿函数作为线程的传入参数

```c++
class BackgroundTask{
    void operator()(){
        void doSomething();
        void doSomethingElse();
    }
}

void main(){
    BackgroundTask f;
    std::thread thd(f);
}
```

######     2.1.2    线程等待         

问题1     ***thd持有主线程的局部变量所使用的线程等待***

新线程上的函数持有主线程所在函数局部变量的指针或者引用，但主线程所在的函数运行结束后，新线程可能仍在执行，由于主线程所在的函数已经结束，其局部变量被销毁，那么其引用和指针也变成了野指针，这是致命的                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

```c++
struct Func{
  int& m_i;
  Func(int& i) : m_i(i){}
  void operator()(){
      for(size_t j=0;j<10000;j++){
          doSomething(m_i); ①<----------------------隐患 可能访问已经被销毁的内存数据
      }
  }
};

void function(){
    int localVar=0;
    Func func(localVar);/*构造函数执行后，m_i~i~localVar m_i i 是localVar的引用*/
    std:: thread thd(func);
    thd.detach();②<------------------function的主线程不必等到thd的线程结束后再结束，换句话说，主线程干完该干的活就可以结束了
}③<-----------------------------------thd可能仍在运行，而主线程已经结束
/*在主线程结束后thd线程仍然在做循环计算，使用到m_i也就是localVar这块内存里的数据，但是主线程结束了，function退出了，localVar这块内存已经被销毁了，m_i i 也就成了野指针*/

     主线程                                         thd
     ---------------------------------------------------------------------------------------
     初始化local变量 localVar
     ---------------------------------------------------------------------------------------
     构造func对象
     ---------------------------------------------------------------------------------------
     启动新线程thd
     ---------------------------------------------------------------------------------------
      								thd新线程启动
     ---------------------------------------------------------------------------------------
         							调用仿函数func()
     ---------------------------------------------------------------------------------------
     分离新线程thd					 运行func()
         							调用doSomething()
                                    运行doSomething()进而使用局部变量localVar
     ---------------------------------------------------------------------------------------
     主线程结束 销毁局部变量localVar    仍在运行
     ---------------------------------------------------------------------------------------
     function()退出                  仍在运行 导致localVar未定义行为
     ---------------------------------------------------------------------------------------
         							 程序报错结束
     ---------------------------------------------------------------------------------------











```

​      	解决方法  让主线程等待新线程thd的完成 只许将detach()换为join()即可

​	  

​    	问题2	 ***thd执行的函数出现异常时所使用的线程等待***	

​     	考虑修改后的下述代码，仍可能出现一些异常情况·

```c++
struct Func{
	private:
		int& m_i;
		Func(int& i):m_i(i){}
	public:
		void operator()(){
			for(int j : 1000){
				doSomething(m_i);
			}
	} 
}



void function(){
	int localVar=0;
    Func func(localVar);
    std::thread thd(func);①<-----------如果thd在启动时出现异常，join()会被忽略
    thd.join();
}
```

​		解决方法 ：使用抛出异常机制

​	  

```
struct Func{
private:
	int& m_i;
	Func(int& i):m_i(i){}
public:
	void operator()(){
		for(int j: 10000){
			doSomething(m_i);
		}
	}
}


void function(){
	int localVar=0;
	Func func(localVar);
	try{
		std::thread thd(func);
	}
	catch(){
		throw;
	}
	thd.join();
}

```

​		问题3 ***异常不是出现在新线程执行的函数上，而是出现在主函数里***

​		

```c++
void function(){
    int localVar=0;
    Func func(localVar);
    std::thread thd(func);
    doSomethingInFunction();①<----------------function如果在这里抛出异常那么join也无法执行,即主线程无法等待新线程结束
    thd.join();
}
```

​     	 解决方法  使用try catch机制让抓主线程等待thd结束

​	

```c++
void function(){
    int localVar=0;
    Func func(localVar);
    std::thread thd(func);
    try{
        doSomethingInFunction();
    }
    catch(...){
        thd.join(); ①<-------如果doSomethingInFunction出现异常，被捕获到，先让thd汇合，再抛出异常。
        throw;
    }
    thd.join();②<-------------如果doSomethingInFunction正常执行，thd会在这里汇合
}
```

​		***使用RAII手法代替异常抛出机制***	

​		更优美的手法 使用所谓的RAII（resource acquisition in initialization) ,在析构函数中让线程汇合；

```c++
class ThreadGuard{
	private:
		std::thread& thd;
	public:
		explict ThreadGuard(std::thread& thd):thd(thd){
		}
		~ThreadGuard(){
			if(thd.isjoinable()){①<-------------thd线程只能被汇合一次，检查之前是否已经汇合过
				thd.join();
			}
		}
		ThreadGuard(const ThreadGuard& )=delete;②<-----------------不可缺少
		ThreadGuard& operator=(const thread &)=delete;③<--------------------不可缺少
}


void function(){
    int localVar=0;
    Func func(localVar);
    std::thread thd(func);
    ThreadGuard thdg(thd);
    
    //ThreadGuard thdg2=thdg;④<---------------致命的错误
    
    
    
    doSomethingInFuncation();
}


如果主线程所执行的doSomethingFunction函数不发生异常，那么在function末尾，thdg对象会被析构掉，thd.join()会发生，此时一直停留在末尾处，主线程等待thd线程执行完毕后function正常退出;

如果主线程所执行的doSomethingFuncation函数发生异常,那么此时已经在function末尾，thdg对象会被析构掉，thd.join()会发生，此时一直停留在末尾处，主线程等待thd线程执行完毕后function正常退出;

综上，不采用异常捕获机制，不管doSomethingFuncation是否发生异常，新线程thd都能正常的thd.join()
    
②和③是必要的   为什么拷贝构造函数和重载的=要删除掉？ 
如果出现了④ 会发生如下情况   注意了，thd成员是引用类型，下面的两个thd成员实际是一个， 当thd,thdg被析构掉thd.join()会被调用两次，这是致命的.
    
    thdg    -----------------                         -------------------     thd
    		|      thd --------|------>func<------|              thd     |
    		 ----------------                         --------------------



```

​		

​	***		在后台运行线程thd，让thd处理新任务，detach也不是毫无作用...................***

​			detach在thd使用主线程的局部变量时可能出现问题,在确保detach没有问题的情况下，可以用detach分离线程用来处理其他任务。

```c++
void eidtDocument(const std::string& filename){
    openDocumentAndDesplayGui(filename);
    while(!doneEditing()){
    	userCommand cmd = getUserInput();
        if(cmd.type == openNewDocument){
            std::string newFilename=getFilenameFromUser();
            std::thread thd(editDocument,newFilename);①<---------拿到文件名后启动线程执行
            thd.detach();①-------------------分离线程是可行的，在拿到文件名后主线程不需要等待thd结束后在结束！
        }
        else{
            processUserInput(cmd);③<----------------主线程处理当前任务
        }
    }
}
```

######         2.2																向线程指向的函数传递参数

​		**最简单的情形**

​		

```c++
void ff(int i,const std::string& s){
    doSomethingInCurrent(i,s);
}


int function(){
    std::thread thd(ff,1,"hello");①<-------传递的是一个常量，绑定在引用上，这是不严谨的
    thd.join();
    return 1;
}


int function(){
    string str="hello";
    std::thread thd(ff,1,str);②<--------这样比①严谨
    thd.join();
    return 1;
}

thd----->ff(1,str)------>doSomethingInCurrent(i,s)----------
    
    --------                         -------
 -->|   i  | 形参         ------->   |  hello|  str(s) function的局部变量
    --------                         -------

```

​         **传 的参数是一个指针 可能会出现前面出现的问题**

```c++
void funcation(int i ,const string& s){
    doSomething(i,str);
}

void oops(int someParm){
    char buffer[256];
    sprintf(buffer,"%i",someParm);
    std::thread thd(function,3,buffer);①<------------
 	thd.detach();   
}
①很可能出现这样的问题，在oops退出之前，buffer正在程序内部转换为string类型，此时可能buffer这个数组已经被销毁，出现转换时的未定义行为；
    



```

​		 ***解决方法  在thread调用构造函数之前或者说在thd执行函数之前将buffer转换为string类型***

​		

```c++
void function(int i,const string& s){
    doSomething(i,str);
}

void oops(int someParm){
    char buffer[256];
    sprintf(buffer,"%i",someParm);
	std::thread thd(function,3,std::string(buffer));①<---------在thread的构造函数执行之前就转型
    thd.detach();
}
```

​     ***注意到s是引用类型，在oops结束后可能仍会出现s未定义的行为这里使用形式参数的值复制来传递***

```c++
void  function(int i,const string s){①<-------------参数被复制在function里，虽然在运行时要耗费掉一些空间，但不会抛出异常完美；
	doSomething(i,str);
}

void oops(int someparm){
	char buffer[256];
	sprintf(buffer,"%i",someSparm);
	std::thread thd(function,3,std::string(buffer));
	thd.detach();
}

```

​		***我们知道，在thd的构造函数里的函数参数在其thd内部时会发生如下操作，将参数复制一份，并将其变为move-only（常量）传递给function;***

​		***我们首先要明白顺便复习一下***

​	    

```c++
void function(const string & value){
	doSomething(value);
}

int main(){
    
	function("mark");    ①<----------将一个常量绑定在常量引用上是可行的function内存结构如下
    return 1;
}

value--->   用value来操纵这片内存
 ------------
|     mark   |
 ------------

```

​		

```c++
void function(string& value){
    doSomething(value);
}

int main(){
    function("hello")①<-------这是不可行的，将常量绑定在变量引用上，不合法
    return 1;
}


```

​       ***如果thd执行的函数function(string& value)时你可要小心了！***

```c++
void function(string& value){
    
}

void oops(widgetID w){
    widgetData data;
    std::thread thd(function,data);
    ②<-----严重的错误  thd调用的时候默认使用thd-->function(dataCopy) dataCopy是data副本的常量形式犯了将一个常量绑定在变量引用身上的错误！ 
    displayStatus();
    thd.join();
    processWidgetData(data);
}
```

```c++
void function(string& value){
	
}

void oops(widgetID w){
	widgetData data;
	std::thread thd(function,std::ref(data));①<-----告诉thd你传参数的时候直接传递data本身；将一个变量绑定在value身上就没有什么问题了；
    thd.join();
}

```

​		***2.3 移交线程的归属权***

​	  

```c++
void someFunction();
void someOtherFunction();
std::thread thd1(someFunction);①<----启动新线程thd1
std::thread thd2=std::move(thd1);②<----将新线程thd1的归属权显示的转交给thd2
thd1=std::thread(someOtherFunction);③<----匿名构造一个匿名的新线程将它的归属权隐式的转交给t1
std::thread thd3; ④<-------构造一个thd3
thd3=std::move(thd2); ⑤<-------将thd2的的归属权显示的转交给thd3
thd1=std::move(thd3);⑥<------将thd3的归属权转交给thd1，thd1已经拥有someOtherFunction()的归属权，无法再接收归属权；

```

​      ***总结： 像之前我们必须明确，在thread对象析构掉之前我们是要将thread对象汇合还是分离线程？同样的在这里，转交线程的归属权也有类似的原则，如果一个线程已经有了归属权，就不能再转交给它其他的归属权了；***

 





​		***对前面的thread_guard类进行修改，我们就可以在构造线程的时候，并将线程的归属权移交给这个类的一个对象，只要将线程的归属权转移给某个thread_guard对象，那么其他thread_guard对象和thread对象就无法执行汇合和分离；我们来改进thread_guard，命名为scoped_thread,它的首要目标是在对象离开作用域被析构掉前，确保线程已经完结***！



```c++
class ScopedThread{
  private:
    std::thread thd;
  public:
    explict ScopedThread(std::threrad _thd):thd(std::move(_thd)){①<----将线程移交给类的内部对象
    	if(!thd.joinable()){②<------在构造函数判断thd是否可以汇合如果已经汇合过则抛出异常
            <----------如果已经汇合过了说明线程已经thd指向的函数已经执行完毕
            throw std::logic_error("Thread can not joinable! ");
        }
    }
    ~ScopedThread(){
        thd.join();③<--------------只有当join语句真正结束后thd才投入执行
    }
    /*拷贝构造函数和重载的=要删除掉，这是必要的，原理前面已经讲过，如果不删掉，可能调用两次func*/
    /*
    		----------------                      -------------
    		|        thd1   |----->func<-------- |     thd2    |
    		----------------                     ---------------
    */
    ScopedThread(const ScopedThread& )=delete;
    ScopedThread& operator=(const ScopedThread& )=delete;
    
    
    
	
    
    
};


struct Func{
    void operator()(int someLocalVar){
        doSomething(someLocalVar);
    }
};

void function(){
    int local=10;
    Func func;
    ScopedThread sthd(std::thread(func,local);~ScopedThread sthd(std::thread(func(local)))④ 
    doSomethingInCurrentThread();
                      
函数的末尾---------->⑤}⑥<---------------------------跳出函数function
                      
                      
                      
注意到上述的参数都是值传递 所以仔细分析会发生:
执行④语句由内到外:
   ------------
   |   匿名线程对象|----->func(local) 之后sthd构造函数之后的结构
   ------------                    
                      
   -------------
   |   匿名线程对象|----->func(local) <------sthd.thd
   --------------      
执行到⑤
    匿名线程对象被销毁 
    sthd.thd------>func(local)
    sthd对象调用析构函数
    sthd.join()执行 
    sthd.thd开始执行指向的函数func(local) 并且主线程一直在⑤处等待func(local)的执行完毕
    执行⑥ 跳出函数function
    
                      

```

​     ***c++20的joining_thread类***

```c++
class JoiningThread{
    private:
    	std::thread thd;
    public:
    
    	JoiningThread()  noexcept=default;
    	
    	explict JoiningThread(std::thread& _thd)  noexcept : thd(std::move(_thd))	{	}
		
  		explict JoiningThread(JoiningThread&& otherObject)  noexcept:
    	thd(std::move(otherObject.thd){}
                                                                            
        JoiningThread& operator=(JoiningThread&& otherObject)  noexcept{
            if(!this->thd.joinable){
                throw std::logic_error("thd can not joinable ! ");
            }
            this->thd=std::move(otherObject.thd);
            return *this;
        }
                                                                            
		JoiningThread& operator=(std::thread  _thd)  noexcept{
            if(!this->thd.joinable()){
                throw std::logic_error("thd can not joinable");
            }
            this->std=std::move(_thd);
            return *this;
        }
            
        ~JoiningThread()  noexcept{  this->thd.join()  }
        /*使用了重载的赋值 大概也能使用拷贝构造*/
        JoiningThread(const JoiningThread& otherObject)=default;
    public:
        inline void swap(JoiningThread& otherObject)  noexcept{
            this->thd.swap(otherObejct.thd);
        }
            
        inline std::thread::id getThreadID() const  noexcept{
            return this->thd.get_id();
        }
            
        inline bool joinable() const  noexcept { return this->thd.joinable(); }      
        inline void join() const   { this->thd.join(); }
        inline void detach() const { this->thd.detach(); }
        inline std::thread& asThread() noexcept { return this->thd; }
        inline const std::thread& asThread const noexcept { return this->thd; }
            
}
                  
void ff(){
    std::thread thd(func);
    JoiningThread jthd(thd);
}
        
            
                
```

​       ***生成一个存放线程的容器并让它们依次执行***

```
void func(unsigned int i);

void function(){
    std::vector<std::thread> threadVector; ①<------------
    
    for(unsigned int i=0;i<3;i++){
        threadVector.emplace_back(func,i); ②<---------
    }
    
    for(auto& thread : threadVector){ ③<--------
        thread.join();
   }
}
  
分析
 ①           -------------
            |             |     threadVector
             ------------
 
 ②
            ----------------------------------
            | thread类型| thread类型| thread类型|   threadVector
            ----------------------------------
            
            --------------------------------------------------------
            | thread(func,0) | thread(func,1)  | thread(func.2)     |  threadVector
            --------------------------------------------------------
            
            ----------------------------------
            | thd1     | thd2      |  thd3    |
            ----|-----------|-----------|-----
                |           |           |
                |           |           |
                 func(1)     func(2)     func(3)
  ③
        thd1管理func(1)执行       thd2管理func(2)执行          thd3管理func(3)执行
```

​       ***2.4           在运行线程时选择线程的数量，用一个并行版来实现累加器*** 

```c++
template<typename Iterator,typename T>
struct  AccumulateBlock{
    void operator()(Iterator firstIterator,Iterator lastItertor,T& result){
        result=std::accumulate(firstIterator,lastIterator,result);
    }
}


template<typename Iterator,typename T>
T parallelAccumulate(Iterator firstIterator,lastIterator,T init){
    const unsigned long length=std::distance(firstIterator,lastIterator);
    if(length==0){ return init; }
    /*maxThreads经验值，length<=25 1个线程  25<length<=50 2个线程 ......*/
    const unsigned long minPerThread=25;
    const unsigned long maxThreads=(length+minPerThread-1)/minPerThread;
    /*halfWareThreads的值可能非常大...*/
    const unsigned long halfWareThreads=std::thread::hareware_concurrency();
    /*numThreads实际创建的线程数,假设length=51也就是有51个待计算的元素，那么maxThreads=3，实际开启的线程数numThreads=3*/
    const unsigned int  numThreads=std::min(halfWareThreads ?halfWareThreads :2,maxThreads);
    /*将51个元素分为三个块，每个线程处理一个块，每个块的元素个数*/
    const unsigned int blockSize=length / numThreads;
    /*用一个容器计算每个块产出的结果*/
    std::vector<T>  resultVector(numThreads);
    /*需要创建的线程数量，当前有一个主线程，只需要在创建两个线程即可*/
    std::vector<std::thread>  threadVector(numThreads-1);
    /*迭代器指向块的起始位置*/
    Itertor blockStart=firstIterator;
    for(unsigned int index=0;index<numThreads-1;index++){
        /*blockEnd初始化*/
        iterator blockEnd= blockStart;
        /*将blockEnd往后移动blockSize*/
        std::advance(blockEnd,blockSize);
        /*为每个块依次创建一个线程*/
         threadVector[index]=std::thread(AcculateBlock<Iterator,T>(),blockStart,blockEnd,std::ref(resultVector.at(index)));
        blockStart=blockEnd;
    }
    /*在主线程中计算最后一个块*/
    AccumulateBlock<iterator,T>() (blockStart,last,resultVector.at(numThreads-1));
    /*对每个线程执行汇合*/
    for(auto& thread : threadVector){
        thread.join();
    }
    return std::accumulate(resultVector.begin(),resultVector.end(),init);
}
```

​	 ***<u>2.5 识别线程</u>***

```c++
线程ID的专属类型是std::thread::id; 如果thd关联了执行线程，调用get_id()，即可得到线程的ID，如果thd没有关联执行线程，则返回一个std::thread::id对象，表示线程还没投入执行；当前线程的ID可以调用std::thread::get_id();thread::id是可以比较大小的，如果两个thd的id相等，表示它们是相同的线程或者表示它们都没有投入执行；如果不相等则表示它们是不同的线程或者其中一个表示一个线程另一个线程不存在；
std::thread::id常用于识别线程，以判断它们是否需要执行某些任务。

std::thread::id masterThread;
void function(){
    /*主线程做一些特有的任务*/
    if(std::this_thread::get_id()==masterThread){
        doMasterThreadWork();
    }
    /*对一些共有的任务并发的交给其他线程执行*/
    doCommonWork();
}
```

